name: Ruff Lint and Fix

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-and-fix:
    name: Lint and Fix Python Code with Ruff
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Run Ruff Lint
        run: |
          ruff check .

      - name: Run Ruff Fix
        run: |
          ruff check . --fix

      - name: Commit and Push Fixes
        if: success() && github.event_name == 'push'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Fix Python code using Ruff"
          git push
        continue-on-error: true
